apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quay-enterprise

resources:
- quay-enterprise-ns.yaml
- quay-registry-quayregistry.yaml

secretGenerator:
- files:
  - config.yaml=conf/config.yaml
  name: quay-registry-config-bundle
  type: Opaque

configurations:
- kustomizeconfig.yaml
