apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
spec:
  components:
  - kind: clair
    managed: true
  - kind: postgres
    managed: true
  - kind: objectstorage
    managed: false
  - kind: redis
    managed: true
  - kind: horizontalpodautoscaler
    managed: false
  - kind: route
    managed: true
  - kind: mirror
    managed: true
  - kind: monitoring
    managed: true
  configBundleSecret: quay-registry-config-bundle
